#!/bin/bash/

du -sch "/media/sistemas/PRESTAMO/Marketing/Firmas/EAO/Firmas Antiguas"
du -sch "/media/sistemas/PRESTAMO/Marketing/Firmas/EAO/Firmas Año Nuevo 2016"
du -sch "/media/sistemas/PRESTAMO/Marketing/Firmas/EAO/Thumbs.db"
du -sch "/media/sistemas/PRESTAMO/Marketing/Firmas/Firmas_cargos_personal (2).xlsx"
du -sch "/media/sistemas/PRESTAMO/Marketing/Firmas/Firmas_cargos_personal.xlsx"
du -sch "/media/sistemas/PRESTAMO/Marketing/Firmas/Lexmark"
du -sch "/media/sistemas/PRESTAMO/Marketing/Firmas/ML"
du -sch "/media/sistemas/PRESTAMO/Marketing/Firmas/Outlet Multifuncionales Firmas"
du -sch "/media/sistemas/PRESTAMO/Marketing/Firmas/Samsung"
du -sch "/media/sistemas/PRESTAMO/Marketing/Firmas/Sharp"
du -sch "/media/sistemas/PRESTAMO/Marketing/Firmas/Thumbs.db"
du -sch "/media/sistemas/PRESTAMO/Marketing/Firmas/TIM"
du -sch "/media/sistemas/PRESTAMO/Marketing/Firmas/Xerox"
du -sch "/media/sistemas/PRESTAMO/Marketing/Folleto ECB"
du -sch "/media/sistemas/PRESTAMO/Marketing/Fotos"
du -sch "/media/sistemas/PRESTAMO/Marketing/FOTOS (Julio 2017)"
du -sch "/media/sistemas/PRESTAMO/Marketing/Gafetes"
du -sch "/media/sistemas/PRESTAMO/Marketing/Gif"
du -sch "/media/sistemas/PRESTAMO/Marketing/Gota y Flor"
du -sch "/media/sistemas/PRESTAMO/Marketing/Identidad Corporativa"
du -sch "/media/sistemas/PRESTAMO/Marketing/Imagenes Sharp"
du -sch "/media/sistemas/PRESTAMO/Marketing/jelly_fish.mp4"
du -sch "/media/sistemas/PRESTAMO/Marketing/Logos"
du -sch "/media/sistemas/PRESTAMO/Marketing/Lonas"
du -sch "/media/sistemas/PRESTAMO/Marketing/Mails Multifuncionales"
du -sch "/media/sistemas/PRESTAMO/Marketing/Mercado Libre"
du -sch "/media/sistemas/PRESTAMO/Marketing/MY POS"
du -sch "/media/sistemas/PRESTAMO/Marketing/OutletMultifuncionales"
du -sch "/media/sistemas/PRESTAMO/Marketing/Paginas Andy"
du -sch "/media/sistemas/PRESTAMO/Marketing/Pendientes Leslie 21jul14"
du -sch "/media/sistemas/PRESTAMO/Marketing/Postales Navidad"
du -sch "/media/sistemas/PRESTAMO/Marketing/Precios 2017"
du -sch "/media/sistemas/PRESTAMO/Marketing/Promociones"
du -sch "/media/sistemas/PRESTAMO/Marketing/Propaganda y folletos"
du -sch "/media/sistemas/PRESTAMO/Marketing/Recursos"
du -sch "/media/sistemas/PRESTAMO/Marketing/Recursos Graficos"
du -sch "/media/sistemas/PRESTAMO/Marketing/Resultado del Pago.pdf"
du -sch "/media/sistemas/PRESTAMO/Marketing/SEO"
du -sch "/media/sistemas/PRESTAMO/Marketing/Servicios Administrados"
du -sch "/media/sistemas/PRESTAMO/Marketing/Smartify"
du -sch "/media/sistemas/PRESTAMO/Marketing/Software Samsung"
du -sch "/media/sistemas/PRESTAMO/Marketing/.TemporaryItems"
du -sch "/media/sistemas/PRESTAMO/Marketing/Tiendas Oficiales"
du -sch "/media/sistemas/PRESTAMO/Marketing/Tutoriales C.Facebook"
du -sch "/media/sistemas/PRESTAMO/Marketing/Uniformes"
du -sch "/media/sistemas/PRESTAMO/Marketing/Video_Papercute"
du -sch "/media/sistemas/PRESTAMO/Marketing/Videos"
du -sch "/media/sistemas/PRESTAMO/Marketing/Videos Transito"
du -sch "/media/sistemas/PRESTAMO/Marketing/Wallpaper"
du -sch "/media/sistemas/PRESTAMO/Marketing/Web"
du -sch "/media/sistemas/PRESTAMO/Marketing/Xerox"
du -sch "/media/sistemas/PRESTAMO/Marketing/2017"
du -sch "/media/sistemas/PRESTAMO/Marketing/AdWords.pdf"
du -sch "/media/sistemas/PRESTAMO/Marketing/Animacion"
du -sch "/media/sistemas/PRESTAMO/Marketing/Archivos"
du -sch "/media/sistemas/PRESTAMO/Marketing/Base de Datos"
du -sch "/media/sistemas/PRESTAMO/Marketing/Catalogos"
du -sch "/media/sistemas/PRESTAMO/Marketing/Correos"
du -sch "/media/sistemas/PRESTAMO/Marketing/DesarrolloWeb"
du -sch "/media/sistemas/PRESTAMO/Marketing/Diseño"
du -sch "/media/sistemas/PRESTAMO/Marketing/Dominios"
du -sch "/media/sistemas/PRESTAMO/Marketing/Drive"
du -sch "/media/sistemas/PRESTAMO/Marketing/.DS_Store"
du -sch "/media/sistemas/PRESTAMO/Marketing/EAO DS Mercadotecnia"
du -sch "/media/sistemas/PRESTAMO/Marketing/Etiquetas"
du -sch "/media/sistemas/PRESTAMO/Marketing/Exposiciones"
du -sch "/media/sistemas/PRESTAMO/Marketing/Firmas/(2).DS_Store"
du -sch "/media/sistemas/PRESTAMO/Marketing/Firmas/.DS_Store"
du -sch "/media/sistemas/PRESTAMO/Marketing/Firmas/EAO/(2).DS_Store"
du -sch "/media/sistemas/PRESTAMO/Marketing/Firmas/EAO/.DS_Store"
du -sch "/media/sistemas/PRESTAMO/Marketing/Firmas/EAO/Firmas 2011 v1"
du -sch "/media/sistemas/PRESTAMO/Marketing/Firmas/EAO/Firmas 2011 v2"
du -sch "/media/sistemas/PRESTAMO/Marketing/Firmas/EAO/Firmas 2014"
du -sch "/media/sistemas/PRESTAMO/Marketing/Firmas/EAO/Firmas 2015"
du -sch "/media/sistemas/PRESTAMO/Marketing/Firmas/EAO/Firmas 2017/FIRMA_EAODS_newlogo (2).psd"
du -sch "/media/sistemas/PRESTAMO/Marketing/Firmas/EAO/Firmas 2017/FIRMA_EAODS_newlogo (3).psd"
du -sch "/media/sistemas/PRESTAMO/Marketing/Firmas/EAO/Firmas 2017/FIRMA_EAODS_newlogo (4).psd"
du -sch "/media/sistemas/PRESTAMO/Marketing/Firmas/EAO/Firmas 2017/FIRMA_EAODS_newlogo - facturacion y cobranza (2).psd"
du -sch "/media/sistemas/PRESTAMO/Marketing/Firmas/EAO/Firmas 2017/FIRMA_EAODS_newlogo - facturacion y cobranza.psd"
du -sch "/media/sistemas/PRESTAMO/Marketing/Firmas/EAO/Firmas 2017/FIRMA_EAODS_newlogo.psd"
